services:
  service:
    build:
      context: ./service/
      dockerfile: Dockerfile.test
      args:
        HOST_UID: ${HOST_UID:-1000}
        HOST_GID: ${HOST_GID:-1000}
        HOST_USERNAME: ${HOST_USERNAME:-user}
        HOST_GROUPNAME: ${HOST_GROUPNAME:-group}
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./service/app:/app
      - ./service/data:/data
