name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Show Docker versions (debug)
        run: |
          docker version
          docker compose version
      - name: Build containers
        env:
          DOCKER_BUILDKIT: 1
          HOST_UID: "1000"
          HOST_GID: "1000"
          DISPLAY: ":1"
          HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
          HOST_GROUPNAME: ${{ secrets.HOST_GROUPNAME }}
        run: |
          docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm service_test
      - name: Run service tests
        run: |
          docker compose -f docker-compose.test.yml run --rm   --entrypoint /bin/sh service_test -lc '
              python -m coverage run -m pytest -q
          '
      - name: Upload coverage xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: service/reports/ci/coverage.xml
          if-no-files-found: error
      - name: Cleanup
        env:
          DOCKER_BUILDKIT: 1
          HOST_UID: "1000"
          HOST_GID: "1000"
          DISPLAY: ":1"
          HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
          HOST_GROUPNAME: ${{ secrets.HOST_GROUPNAME }}
        if: always()
        run: |
          docker compose  down -v --remove-orphans
